version: '2'

services:
    php:
        build: .\conf
        volumes:
            - ..\..\PhpstormProjects:/var/www/html
            #- ../logs/app:/var/www/html/app/logs
            #- .\conf\php.ini:/usr/local/etc/php/php.ini
    httpd:
        image: nexus.prod.uci.cu/httpd:2.4
    mariadb:
        image: nexus.prod.uci.cu/mariadb:5.5
        ports:
            - "3306:3306"
        volumes:    
            - mariadb_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: d535e4928584ac2bca68865e6246da4c
            MYSQL_DATABASE: sitio_db
            MYSQL_PASSWORD: d535e4928584ac2bca68865e6246da4c
    phpmyadmin:
        image: nexus.prod.uci.cu/phpmyadmin/phpmyadmin:4.6
        depends_on:
           - mariadb
        ports:
           - '8080:80'
           - '444:443'
        environment:
           - PHPMYADMIN_ALLOW_NO_PASSWORD=true
           - PHPMYADMIN_ALLOW_ARBITRARY_SERVER=true
        volumes:
           - phpmyadmin_data:/data/phpmyadmin
           - php_data:/data/php
           - httpd_data:/data/httpd
    
volumes:
  mariadb_data:
    driver: local
  phpmyadmin_data:
    driver: local
  php_data:
    driver: local
  httpd_data:
    driver: local